# Generated by Django 2.0.1 on 2018-02-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhistJoueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
            },
        ),
        migrations.CreateModel(
            name='WhistPartie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Le nom de la partie devra être unique', max_length=50, verbose_name='Nom de la partie')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de la partie')),
                ('cartes', models.IntegerField(default=0, help_text='Nombre de cartes maximum par joueurs qui seront distribuées', verbose_name='Nombre de cartes max / joueur')),
                ('carte', models.IntegerField(default=0, verbose_name='Nombre de carte du jeu')),
                ('jeu', models.IntegerField(default=0, verbose_name='n° du jeu en cours')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='WhistParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=99)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whist.WhistJoueur', verbose_name='Joueur')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whist.WhistPartie', verbose_name='Partie')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='WhistJeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu', models.IntegerField(default=0, verbose_name='Jeu')),
                ('pari', models.IntegerField(default=0, verbose_name='Pari')),
                ('real', models.IntegerField(default=0, verbose_name='Réalisé')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whist.WhistParticipant')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
            },
        ),
    ]
