# Generated by Django 2.0.1 on 2018-01-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhistJeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu', models.IntegerField(default=0, verbose_name='Jeu')),
                ('pari', models.IntegerField(default=0, verbose_name='Pari')),
                ('real', models.IntegerField(default=0, verbose_name='Réalisé')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
            },
        ),
        migrations.CreateModel(
            name='WhistJoueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
            },
        ),
        migrations.CreateModel(
            name='WhistParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whist.WhistJoueur', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='WhistPartie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Le nom de la partie devra être unique', max_length=50, verbose_name='Nom de la partie')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de la partie')),
                ('jeu', models.IntegerField(default=0, verbose_name='Nombre de jeux (de tours) de la partie')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.AddField(
            model_name='whistparticipant',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whist.WhistPartie', verbose_name='Partie'),
        ),
        migrations.AddField(
            model_name='whistjeu',
            name='joueur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whist.WhistJoueur'),
        ),
        migrations.AddField(
            model_name='whistjeu',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whist.WhistPartie'),
        ),
    ]
