# Generated by Django 2.0.1 on 2018-01-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistpartie',
            name='carte',
            field=models.IntegerField(default=0, verbose_name='Nombre de carte du jeu'),
        ),
        migrations.AddField(
            model_name='whistpartie',
            name='cartes',
            field=models.IntegerField(default=0, help_text='Nombre de cartes maximum par joueurs qui seront distribuées', verbose_name='Nombre de cartes max / joueur'),
        ),
        migrations.AlterField(
            model_name='whistpartie',
            name='jeu',
            field=models.IntegerField(default=0, verbose_name='n° du jeu en cours'),
        ),
    ]
