# Generated by Django 2.0.1 on 2018-02-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistjeu',
            name='carte',
            field=models.IntegerField(default=0, verbose_name='Nbre de cartes'),
        ),
    ]
