# Generated by Django 2.0.1 on 2018-01-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0002_auto_20180131_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistparticipant',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
