# coding: utf-8
# Generated by Django 2.0.1 on 2018-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0004_auto_20180202_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistjeu',
            name='donneur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whistparticipant',
            name='donneur',
            field=models.IntegerField(default=0),
        ),
    ]
