# Generated by Django 2.0.1 on 2018-02-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0005_auto_20180206_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistpartie',
            name='jeu',
            field=models.IntegerField(default=0, verbose_name='n° du jeu en cours'),
        ),
    ]
