# Generated by Django 2.0.2 on 2018-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0006_whistpartie_jeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistjeu',
            name='pari',
            field=models.IntegerField(choices=[(0, '0 pli'), (1, '1 pli'), (2, '2 plis'), (3, '3 plis')], default=0, verbose_name='Pari'),
        ),
    ]
