# Generated by Django 2.0.2 on 2018-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0008_auto_20180222_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistjeu',
            name='pari',
            field=models.IntegerField(default=0, help_text='Le nombre de plis ne peut pas dépasser le nombre de cartes', verbose_name='Pari'),
        ),
    ]
