# Generated by Django 2.0.2 on 2018-04-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0011_auto_20180319_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistpartie',
            name='modified',
            field=models.BooleanField(default=False, verbose_name="L'un des jeux a été modifié"),
        ),
        migrations.AddField(
            model_name='whistpartie',
            name='qparticipant',
            field=models.IntegerField(default=0, verbose_name='Nombre de joueurs'),
        ),
    ]
