# Generated by Django 2.0.2 on 2018-04-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0012_auto_20180410_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistjeu',
            name='donneur',
            field=models.BooleanField(default=0),
        ),
    ]
