# Generated by Django 2.0.2 on 2018-03-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotJeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu', models.IntegerField(default=0, verbose_name='N° du tour')),
                ('pari', models.TextField(default='...', verbose_name='Contrat')),
                ('real', models.IntegerField(default=99, verbose_name='Réalisé')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('medal', models.IntegerField(default=0, verbose_name='Médaille')),
                ('donneur', models.BooleanField(default=False, verbose_name='Donneur')),
                ('prenneur', models.BooleanField(default=False, verbose_name='Prenneur')),
                ('partenaire', models.BooleanField(default=False, verbose_name='Partenaire appelé')),
                ('primes', models.IntegerField(default=0, verbose_name='Primes')),
                ('ptbout', models.BooleanField(default=False, verbose_name='Petit au bout (10 points)')),
                ('misere1', models.BooleanField(default=False, verbose_name="Misère d'atout (10 points)")),
                ('misere2', models.BooleanField(default=False, verbose_name='Misère de tête (10 points)')),
                ('poignee1', models.BooleanField(default=False, verbose_name='Poignée (20 points)')),
                ('poignee2', models.BooleanField(default=False, verbose_name='Double Poignée (30 points)')),
                ('poignee3', models.BooleanField(default=False, verbose_name='Triple Poignée (40 points)')),
                ('grchelem', models.BooleanField(default=False, verbose_name='Grand Chelem annoncé (400 points)')),
                ('gchelem', models.BooleanField(default=False, verbose_name='Grand Chelem non annoncé (200 points)')),
                ('ptchelem', models.BooleanField(default=False, verbose_name='Petit Chelem annoncé (200 points)')),
                ('pchelem', models.BooleanField(default=False, verbose_name='Petit Chelem non annoncé (100 points)')),
                ('gpchelem', models.BooleanField(default=False, verbose_name='Grand Chelem annoncé non réalisé (-200 points)')),
                ('ppchelem', models.BooleanField(default=False, verbose_name='Petit Chelem annoncé non réalisé (-100 points)')),
                ('modified', models.BooleanField(default=False, verbose_name='A été modifié')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
            },
        ),
        migrations.CreateModel(
            name='TarotJoueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='inconnu', help_text='Le compte propriétaire', max_length=50, verbose_name='Compte')),
                ('pseudo', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
            },
        ),
        migrations.CreateModel(
            name='TarotParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=99)),
                ('donneur', models.IntegerField(default=0)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot.TarotJoueur', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='TarotPartie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='inconnu', help_text='Le compte propriétaire', max_length=50, verbose_name='Compte')),
                ('name', models.CharField(help_text='Le nom de la partie sera unique', max_length=50, verbose_name='Nom de la partie')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de la partie')),
                ('jeu', models.IntegerField(default=0, verbose_name='n° du jeu en cours')),
                ('qparticipant', models.IntegerField(default=0, verbose_name='Nombre de joueurs')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.AddField(
            model_name='tarotparticipant',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot.TarotPartie', verbose_name='Partie'),
        ),
        migrations.AddField(
            model_name='tarotjeu',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot.TarotParticipant'),
        ),
    ]
