# Generated by Django 2.0.2 on 2018-03-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotJeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu', models.IntegerField(default=0, verbose_name='N° du tour')),
                ('pari', models.IntegerField(default=0, verbose_name='Pari')),
                ('real', models.IntegerField(default=0, verbose_name='Réalisé')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('medal', models.IntegerField(default=0, verbose_name='Médaille')),
                ('donneur', models.IntegerField(default=0, verbose_name='Donneur')),
                ('partenaire', models.IntegerField(default=0, verbose_name='Partenaire appelé')),
                ('misere1', models.IntegerField(default=0, verbose_name="Misère d'atout")),
                ('misere2', models.IntegerField(default=0, verbose_name='Misère de tête')),
                ('poignee1', models.IntegerField(default=0, verbose_name='Double Poignée')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
            },
        ),
        migrations.CreateModel(
            name='TarotJoueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='inconnu', help_text='Le compte propriétaire', max_length=50, verbose_name='Compte')),
                ('pseudo', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
            },
        ),
        migrations.CreateModel(
            name='TarotParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=99)),
                ('donneur', models.IntegerField(default=0)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot.TarotJoueur', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='TarotPartie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='inconnu', help_text='Le compte propriétaire', max_length=50, verbose_name='Compte')),
                ('name', models.CharField(help_text='Le nom de la partie sera unique', max_length=50, verbose_name='Nom de la partie')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de la partie')),
                ('jeu', models.IntegerField(default=0, verbose_name='n° du jeu en cours')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.AddField(
            model_name='tarotparticipant',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot.TarotPartie', verbose_name='Partie'),
        ),
        migrations.AddField(
            model_name='tarotjeu',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot.TarotParticipant'),
        ),
    ]
