# Generated by Django 2.0.2 on 2018-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotpartie',
            name='nb_joueur',
            field=models.IntegerField(default=0, verbose_name='Nombre de joueurs'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='gchelem',
            field=models.BooleanField(default=False, verbose_name='Grand Chelem non annoncé (200 points)'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='gpchelem',
            field=models.BooleanField(default=False, verbose_name='Grand Chelem annoncé non réalisé (-200 points)'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='ppchelem',
            field=models.BooleanField(default=False, verbose_name='Petit Chelem annoncé non réalisé (-100 points)'),
        ),
    ]
