# Generated by Django 2.0.2 on 2018-03-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotpartie',
            name='modified',
            field=models.BooleanField(default=False, verbose_name="L'un des jeux a été modifié"),
        ),
    ]
