# Generated by Django 2.0.2 on 2018-03-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotjeu',
            name='bouts',
            field=models.IntegerField(default=0, verbose_name='Bouts'),
        ),
    ]
