# Generated by Django 2.0.2 on 2018-03-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_auto_20180326_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarotpartie',
            old_name='nb_joueur',
            new_name='qparticipant',
        ),
    ]
