# Generated by Django 2.0.2 on 2018-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_tarotjeu_bouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotjeu',
            name='poignee2',
            field=models.IntegerField(default=0, verbose_name='Double Poignée'),
        ),
        migrations.AddField(
            model_name='tarotjeu',
            name='ptbout',
            field=models.IntegerField(default=0, verbose_name='Petit Bout au bout'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='pari',
            field=models.IntegerField(default=0, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='poignee1',
            field=models.IntegerField(default=0, verbose_name='Poignée'),
        ),
    ]
