# Generated by Django 2.0.2 on 2018-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0003_auto_20180326_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotjeu',
            name='pari',
            field=models.TextField(default='.', verbose_name='Contrat'),
        ),
    ]
