# Generated by Django 2.0.2 on 2018-03-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0003_auto_20180321_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotjeu',
            name='chelem',
            field=models.IntegerField(default=0, verbose_name='Chelem'),
        ),
        migrations.AddField(
            model_name='tarotjeu',
            name='poignee3',
            field=models.IntegerField(default=0, verbose_name='Triple Poignée'),
        ),
    ]
