# Generated by Django 2.0.2 on 2018-03-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0004_auto_20180326_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotjeu',
            name='real',
            field=models.IntegerField(default=99, verbose_name='Réalisé'),
        ),
    ]
