# Generated by Django 2.0.2 on 2018-03-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0004_auto_20180321_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotjeu',
            name='chelem',
        ),
        migrations.AddField(
            model_name='tarotjeu',
            name='grchelem',
            field=models.IntegerField(default=0, verbose_name='Grand Chelem'),
        ),
        migrations.AddField(
            model_name='tarotjeu',
            name='ptchelem',
            field=models.IntegerField(default=0, verbose_name='Petit Chelem'),
        ),
    ]
