# Generated by Django 2.0.2 on 2018-03-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0005_auto_20180321_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotjeu',
            name='bouts',
            field=models.IntegerField(default=0, verbose_name='Nombre de Bouts'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='grchelem',
            field=models.BooleanField(default=False, verbose_name='Grand Chelem'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='misere1',
            field=models.BooleanField(default=False, verbose_name="Misère d'atout"),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='misere2',
            field=models.BooleanField(default=False, verbose_name='Misère de tête'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='poignee1',
            field=models.BooleanField(default=False, verbose_name='Poignée'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='poignee2',
            field=models.BooleanField(default=False, verbose_name='Double Poignée'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='poignee3',
            field=models.BooleanField(default=False, verbose_name='Triple Poignée'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='ptbout',
            field=models.BooleanField(default=False, verbose_name='Petit au bout'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='ptchelem',
            field=models.BooleanField(default=False, verbose_name='Petit Chelem'),
        ),
    ]
