# Generated by Django 2.0.2 on 2018-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0005_auto_20180326_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotjeu',
            name='pari',
            field=models.TextField(default='...', verbose_name='Contrat'),
        ),
    ]
