# Generated by Django 2.0.2 on 2018-03-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0006_auto_20180322_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotjeu',
            name='donneur',
            field=models.BooleanField(default=0, verbose_name='Donneur'),
        ),
        migrations.AlterField(
            model_name='tarotjeu',
            name='partenaire',
            field=models.BooleanField(default=0, verbose_name='Partenaire appelé'),
        ),
    ]
