# Generated by Django 2.0.2 on 2018-03-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0006_auto_20180326_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotjeu',
            name='prenneur',
            field=models.BooleanField(default=False, verbose_name='Prenneur'),
        ),
    ]
