# Generated by Django 2.0.2 on 2018-03-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0007_tarotjeu_prenneur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotjeu',
            name='bouts',
        ),
    ]
