# Generated by Django 2.0.2 on 2018-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0008_remove_tarotjeu_bouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotjeu',
            name='modified',
            field=models.BooleanField(default=False, verbose_name='A été modifié'),
        ),
    ]
